In [1]:
from sklearn.model_selection import train_test_split 
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes

In [2]:
x,y = load_diabetes(return_X_y=True)

In [3]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2,test_size=0.2)

In [4]:
lr=LinearRegression()

In [5]:
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [6]:
lr.intercept_

151.88331005254167

In [7]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [8]:
r2_score(y_test,y_pred)

0.4399338661568968

In [9]:
x_train.shape

(353, 10)

In [10]:
import random

In [11]:
class Minibatch:
    def __init__(self,batch_size,learning_rate=0.01,epoches=100):
        self.coef_=None
        self.intercept_=None
        self.lr=learning_rate
        self.epoches=epoches
        self.batch_size=batch_size
    
    def fit(self,x,y):
        self.coef_=np.ones(x.shape[1])
        self.intercept_=0

        for i in range(self.epoches):
            
            for j in range(int(x.shape[0]/self.batch_size)):
                idx=random.sample(range(x.shape[0]),self.batch_size)

                y_hat=np.dot(x[idx],self.coef_)+self.intercept_

                slope_coef=-2*np.dot((y[idx]-y_hat),x[idx])
                slope_intercept=-2*np.mean(y[idx]-y_hat)

                self.coef_=self.coef_-(self.lr*slope_coef)
                self.intercept_=self.intercept_-(self.lr*slope_intercept)

        print(self.intercept_,self.coef_)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_

In [12]:
mn=Minibatch(batch_size=int(x_train.shape[0]/50),learning_rate=0.01,epoches=100)

In [13]:
mn.fit(x_train,y_train)

151.78669837763465 [  30.94910894 -139.81845725  445.34234678  302.30973795  -16.02890073
  -88.49203623 -188.17362834  117.19182907  414.38782075  108.77847298]


In [14]:
y_pred=mn.predict(x_test)
r2_score(y_test,y_pred)

0.4521162442330926

In [24]:
from sklearn.linear_model import SGDRegressor

In [25]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [26]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [27]:
sgd.coef_

array([  66.59853248,  -67.75351854,  335.25912819,  245.63105038,
          9.05432884,  -34.85570865, -179.23042   ,  130.49835442,
        316.91294851,  126.09766781])

In [28]:
sgd.intercept_

array([148.29028612])

In [29]:
y_pred = sgd.predict(x_test)

In [30]:
r2_score(y_test,y_pred)

0.42926747913958674