In [18]:
import pickle
import numpy as np

In [19]:
ohe_sex=pickle.load(open(r"F:\ML\100 days ml\models\ohe_sex.pkl","rb"))
ohe_embarked = pickle.load(open(r'F:\ML\100 days ml\models\ohe_embarked.pkl','rb'))
clf = pickle.load(open(r'F:\ML\100 days ml\models\clf.pkl','rb'))

In [20]:
test_input=np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype="object").reshape(1,7)

In [21]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [22]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\Gargi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [23]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [24]:
test_input_embarked

array([[0., 0., 1.]])

In [25]:
test_input_age = test_input[:,2].reshape(1,1)

In [29]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [30]:
test_input_transformed.shape

(1, 10)

In [31]:
clf.predict(test_input_transformed)

array([1], dtype=int64)